- name: Create directories 
  file:
    path: /opt/services/haproxy
    state: directory
    mode: '0755'

- name: copy configuration files
  template:
    src: "{{ item }}"
    dest: /opt/services/haproxy
  loop: 
    - ./templates/haproxy_configs/.env
    - ./templates/haproxy_configs/docker-compose.yml
    - ./templates/haproxy_configs/haproxy.cfg

- name: run haproxty docker compose file.
  community.docker.docker_compose_v2:
    project_src: "/opt/services/haproxy" 
    files:
      - docker-compose.yml
      