---
apiVersion: v1
data:
  auth: c2lhdmFzaDokYXByMSRST0ZHZDguWCRoa3Zib3ZnY2pxbWNVa1FqM0dpeXIuCgo=
kind: Secret
metadata:
  name: alertmanager-auth
  namespace: monitoring
type: Opaque
---
apiVersion: v1
data:
  auth: c2lhdmFzaDokYXByMSRST0ZHZDguWCRoa3Zib3ZnY2pxbWNVa1FqM0dpeXIuCgo=
kind: Secret
metadata:
  name: prometheus-auth
  namespace: monitoring
type: Opaque

# User: siavash
# Pass: cloudflow
# Command: htpasswd -nbm siavash cloudflow | base64
