---
- name: Update APT package list
  apt:
    update_cache: yes

- name: Install HAProxy
  apt:
    name: haproxy
    state: present

- name: Enable HAProxy to start at boot
  systemd:
    name: haproxy
    enabled: yes

- name: Ensure HAProxy is running
  systemd:
    name: haproxy
    state: started

- name: Copy HAProxy configuration file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    backup: yes
  notify:
    - Restart HAProxy
