---
- hosts: all
  vars:
    ansible_ssh_private_key_file: /Users/siavashmohseni/.ssh/id_rsa
  become: true
  gather_facts: true
  name: setup kubernetes cluster 
  roles:
    - { role: roles/kube, become: True, tags: kubernetes }
