---
- hosts: load-balancer-servers
  vars:
    ansible_ssh_private_key_file: /Users/siavashmohseni/.ssh/id_rsa
  become: true
  gather_facts: true
  name: setup haproxy 
  roles:
    - { role: roles/load-balancer, become: True, tags: haproxy }
