---
- hosts: load-balancer-servers
  vars:
    ansible_ssh_private_key_file: /Users/siavashmohseni/.ssh/id_rsa
  become: true
  gather_facts: true
  name: setup api server load balancer and ingress load balancer 
  roles:
    - { role: roles/load-balancer, become: True, tags: load-balancer }
