version: '3.8'

networks:
  web_net:
    external: true

services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    networks:
      - web_net
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web_net"
      - "traefik.http.routers.haproxy-panel.entrypoints=http"
      - "traefik.http.routers.haproxy-panel.rule=Host(`${HAPROXY_PANEL_SUB}.${DOMAIN_ADDRESS}`)"
      - "traefik.http.routers.haproxy-panel.middlewares=https-redirect"
      - "traefik.http.routers.haproxy-panel-secure.entrypoints=https"
      - "traefik.http.routers.haproxy-panel-secure.rule=Host(`${HAPROXY_PANEL_SUB}.${DOMAIN_ADDRESS}`)"
      - "traefik.http.routers.haproxy-panel-secure.tls=true"
      - "traefik.http.routers.haproxy-panel-secure.tls.options=default"
      - "traefik.http.routers.haproxy-panel-secure.tls.certresolver=mycert"
      - "traefik.http.routers.haproxy-panel-secure.service=haproxy-panel"
      - "traefik.http.services.haproxy-panel.loadbalancer.server.port=8404"
      - "traefik.http.routers.ingress-http.entrypoints=http"
      - "traefik.http.routers.ingress-http.rule=Host(`${INGRESS_HTTP_SUB}.${DOMAIN_ADDRESS}`)"
      - "traefik.http.routers.ingress-http.middlewares=https-redirect"
      - "traefik.http.routers.ingress-http-secure.entrypoints=https"
      - "traefik.http.routers.ingress-http-secure.rule=Host(`${INGRESS_HTTP_SUB}.${DOMAIN_ADDRESS}`)"
      - "traefik.http.routers.ingress-http-secure.tls=true"
      - "traefik.http.routers.ingress-http-secure.tls.options=default"
      - "traefik.http.routers.ingress-http-secure.tls.certresolver=mycert"
      - "traefik.http.routers.ingress-http-secure.service=ingress-http"
      - "traefik.http.services.ingress-http.loadbalancer.server.port=32080"
      - "traefik.http.routers.ingress-https.entrypoints=http"
      - "traefik.http.routers.ingress-https.rule=Host(`${INGRESS_HTTPS_SUB}.${DOMAIN_ADDRESS}`)"
      - "traefik.http.routers.ingress-https.middlewares=https-redirect"
      - "traefik.http.routers.ingress-https-secure.entrypoints=https"
      - "traefik.http.routers.ingress-https-secure.rule=Host(`${INGRESS_HTTPS_SUB}.${DOMAIN_ADDRESS}`)"
      - "traefik.http.routers.ingress-https-secure.tls=true"
      - "traefik.http.routers.ingress-https-secure.tls.options=default"
      - "traefik.http.routers.ingress-https-secure.tls.certresolver=mycert"
      - "traefik.http.routers.ingress-https-secure.service=ingress-https"
      - "traefik.http.services.ingress-https.loadbalancer.server.port=32443"
