kubernetes_version: 1.30

service_subnet: "10.96.0.0/12" 
pod_subnet: "10.244.0.0/16"

domain_name: "cloudflow.ir"

master1_name: "master-server-1"
master2_name: "master-server-2"
master3_name: "master-server-3"

vip_api_name: "vip"
vip_ip_address: "vip.cloudflow.ir"
master1_domain: "master1.cloudflow.ir"
master2_domain: "master2.cloudflow.ir"
master3_domain: "master3.cloudflow.ir"
controlplane_endpoint: "vip.cloudflow.ir:6443"
