version: '3.8'

networks:
  web_net:
    external: true

services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    networks:
      - web_net
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web_net"

      - "traefik.http.routers.haproxy-panel.entrypoints=http"
      - "traefik.http.routers.haproxy-panel.rule=Host(`${HAPROXY_PANEL_SUB}.${DOMAIN_ADDRESS}`)"
      - "traefik.http.routers.haproxy-panel.middlewares=https-redirect"
      - "traefik.http.routers.haproxy-panel-secure.entrypoints=https"
      - "traefik.http.routers.haproxy-panel-secure.rule=Host(`${HAPROXY_PANEL_SUB}.${DOMAIN_ADDRESS}`)"
      - "traefik.http.routers.haproxy-panel-secure.tls=true"
      - "traefik.http.routers.haproxy-panel-secure.tls.options=default"
      - "traefik.http.routers.haproxy-panel-secure.tls.certresolver=mycert"
      - "traefik.http.routers.haproxy-panel-secure.service=haproxy-panel"
      - "traefik.http.services.haproxy-panel.loadbalancer.server.port=8404"

      - "traefik.http.routers.ingress.entrypoints=http"
      - "traefik.http.routers.ingress.rule=Host(`${API_SERVER_SUB}.${DOMAIN_ADDRESS}`)"
      - "traefik.http.routers.ingress.middlewares=https-redirect"
      - "traefik.http.routers.ingress-secure.entrypoints=https"
      - "traefik.http.routers.ingress-secure.rule=Host(`${INGRESS}.${DOMAIN_ADDRESS}`)"
      - "traefik.http.routers.ingress-secure.tls=true"
      - "traefik.http.routers.ingress-secure.tls.options=default"
      - "traefik.http.routers.ingress-secure.tls.certresolver=mycert"
      - "traefik.http.routers.ingress-secure.service=ingress"
      - "traefik.http.services.ingress.loadbalancer.server.port=8090"

